version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
  publisher:
    build: .
    depends_on:
      - mqtt
    volumes:
      - .:/code/
    command: python /code/example_mqtt.py
    environment:
      - VERBOSE=True
  subscriber_1:
    build: .
    volumes:
      - .:/code/
    command: python /code/example_mqtt.py subscribe
    environment:
      - VERBOSE=True
  subscriber_2:
    build: .
    volumes:
      - .:/code/
    command: python /code/example_mqtt.py subscribe
    environment:
      - VERBOSE=True

  subscriber_3:
    build: .
    volumes:
      - .:/code/
    command: python /code/example_mqtt.py subscribe
    environment:
      - VERBOSE=True