version: "3"
services:
  redis:
    image: redis:4.0.5-alpine
  publisher:
    build: .
    depends_on:
      - redis
    volumes:
      - .:/code/
    command: python /code/example.py

  subscriber_1:
    build: .
    volumes:
      - .:/code/
    command: python /code/example.py subscribe

  subscriber_2:
    build: .
    volumes:
      - .:/code/
    command: python /code/example.py subscribe

  subscriber_3:
    build: .
    volumes:
      - .:/code/
    command: python /code/example.py subscribe